### PR TITLE
Dirty fix allowing DockerHub to complete

### PR DESCRIPTION
**Pull request by kevinrue**
DockerHub doesn't seem to like file-backed matrices.

### CODE REVIEW

**Comment by LTLA** [comment]
If that were the case, though it should have failed much earlier in the QC calculations. Can you repro it locally?

**Comment by kevinrue** [comment]
I'm running it now. It's taking its sweet time.

**Comment by kevinrue** [comment]
It crashed, but for a different reason "there is no package called devtools".
Ugh. I'll see if I can debug it in the background, but it's not my top priority, now that I've got a workaround.

**Comment by kevinrue** [comment]
Ok so.. @LTLA 

- Launching the iseedevelopers/isee container
```
docker run \
     -e PASSWORD=bioc \
     -p 8787:8787 iseedevelopers/isee:latest
```
- Cloning the workshop package
```
git clone https://github.com/iSEE/iSEEWorkshopEuroBioc2020.git
```
- Removing the dirty fix from the vignette `dataset.Rmd`
- Mimicking the Dockerfile (installing packages, and building the workshop package)
```r
options(repos = c(CRAN = 'https://cran.r-project.org')); BiocManager::install(ask=FALSE)
options(repos = c(CRAN = 'https://cran.r-project.org')); devtools::install('.', dependencies=TRUE, build_vignettes=TRUE, repos = BiocManager::repositories())
```
causes a `Killed` error that is probably the same as DockerHub
```
   using temporary cache /tmp/RtmpoKGoGu/BiocFileCache
   snapshotDate(): 2020-10-02
   see ?TENxPBMCData and browseVignettes('TENxPBMCData') for documentation
   downloading 1 resources
   retrieving 1 resource
   loading from cache
   Loading required package: ggplot2
   Killed
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> 
E> Loading required package: rhdf5
E> using temporary cache /tmp/RtmpoKGoGu/BiocFileCache
E> snapshotDate(): 2020-10-02
E> see ?TENxPBMCData and browseVignettes('TENxPBMCData') for documentation
E> downloading 1 resources
E> retrieving 1 resource
E> loading from cache
E> Loading required package: ggplot2
E> Killed
Type .Last.error.trace to see where the error occured
```

**Pull request merged**
